sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german
script:
- cd tex
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build Patterns.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build Patterns.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build Architectures.tex
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build Architectures.tex
branches:
  only:
    - master
deploy:
  provider: releases
  api_key:
    secure: $key
  file:
  - _build/Patterns.pdf
  - _build/Architectures.pdf
  skip_cleanup: true
  on:
   branch: master
notifications:
  email: false
